### ISSUE TITLE
Psi4 1.0rc5 / WebMO 16.1.003rc1 Compatibility Issues

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#11]
In the next week or so, the WebMO team is planning on releasing a "final" version of WebMO 16.  In this final WebMO 16 release, we want to include the latest psi4 templates, because the psi4 templates that were included in WebMO 16.1.002 were those from December 2015 and are no longer compatible with the latest releases of psi4.

To start this process, we have built WebMO 16.1.003rc1 which includes the current psi4 templates.  We have installed WebMO 16.1.003rc1 with the latest psi4 binary (Psi4 1.0rc5, Git: Rev {master} a2a32a7) on a Google Cloud Server, which is located at:
    http://104.197.158.156/webmo
You can log in with username = "student" and password = "student"

We have run all the  psi4 calculation types.  The good news is that they all (except SAPT) completed successfully!

However, upon careful inspection of the View Jobs page, we noticed some items that could benefit improvement in the parsing.  Here is the list of items all in one place.  But I am going to open each of them as separate issues, so that we can discuss them separately.  On this page, we should only discuss the process as a whole.
- [x] Changing Bond Order:  It seems that bond orders are being recalculated by the parser, rather than being respected from the input file.  This has the unfortunate consequence of sometimes redefining bond orders that were input by the user, e.g., C-O in HFCO changes from a double bond to a triple bond. It is not typical WebMO behavior for the parsing program to change bond orders of user structures.  (Job 6: CHFO)
- [x] Missing IR Spectra:  IR spectra is not created from transitions and intensities, so nothing is available for Data Viewer (job 7: CHFO - spectrum)
- [x] Molecular Orbitals: The Symmetry of each MO is reported in the output file (right below the energy), but it is evidently not parsed.  Therefore the WebMO View Jobs page does not list the MO symmetries for psi4.  (job 8: CHFO - symmetry)
- [x] SAPT Jobs: SAPT fails, as I naively try to run it.  How do I create a valid input file from within WebMO? (job 9: CHFO - fail)
- [ ] Coordinate Scans: Coordinate scans are always rigid, irrespective of whether optimized or fixed is specified for the other coordinates.  (Can an input file be created that fixes some internal coordinates but optimizes others?  What would such an input file look like?)  This might be a longer term effort rather than a quick fix, in which case we should defer it until WebMO 17.  (job 11: CHOF - fixed)
- [x] 2-D Coordinate Scans:  2-D coordinate scans did not calculate anything (job 16: H2O - 2D)

![psi4jobs](https://cloud.githubusercontent.com/assets/16991493/15723089/d53793f0-280e-11e6-945b-96f3b4ab1035.png)

**Comment by polikw** [comment]
WebMO is now very close to releasing the "final" version of WebMO 16.  I have included the latest github commits on 
     http://104.197.158.156/~webmo/cgi-bin/webmo/login.cgi
which include:
- parse_psi.cgi: fixes changing bond order after an optimization
- psi.tmpl:  activates auto_fragments, and adds a missing comma

If you have not done so yet, please test out this implementation by running a couple of jobs using username = student and password = student .

Items on the above list that are closed are:
- Changing Bond Order: fixed in parse_psi.cgi
- Missing IR intensities: psi4 does not calculate these (yet)

Also, I recommend deferring for now:
- Coordinate scans: only rigid scans are done
  due the complexity of the input file and the possible need to coordinate with the WebMO $geometry variable

However, items from the above list that have NOT been addressed include:
- Molecular Orbitals: symmetries are reported but not parsed
- SAPT jobs: still fail (for me)
- 2-D Coordinate Scans: fail because nothing is calculated

So the question is, do we want to address any of these open issues before we release the "final" version of WebMO 16?

**Comment by loriab** [comment]
In my opinion, it's important to get SAPT working. MO symmetries could be parsed if @bwb314 is interested it. And the 2D scans are less important. No further changes to psi4 1.0 are anticipated that will harm WebMO.

**Comment by polikw** [comment]
Regarding Psi4 1.0rc5 / WebMO 16.1.003rc1 compatibility, I have verified that all the identified issues have been resolved with the latest commits, except non-rgid scans which we are deferring).  So unless someone has a final comment or improvement, we are going to use the current version of the repository for the "final" release of WebMO 16.

That said, we expect to be releasing a preliminary version of WebMO 17 in a few months.  (The key new feature will be a completely new "java-free" editor/viewer written in javascript, for better compatibility with more browsers.)  Future changes to templates, parsing, etc. can be inserted into that WebMO version 17 in fall 2016.

Thank you very much, **team psi4webmo**, for making these changes to the repository and improving the compatibility between Psi4 and WebMO!

**Comment by polikw** [comment]
FYI.  I am shutting down the Google Cloud instance of Psi4 1.0rc5 / WebMO 16.1.003rc1 at:
    http://104.197.158.156/webmo
(username = "student" and password = "student").  I'll keep the virtual disk around for a couple weeks in order to fire it up on request, after which I will delete it permanently.
