### ISSUE TITLE
Missing IR Spectra

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#13]
IR spectra is not created from transitions and intensities, so nothing is available for Data Viewer (job 7: CHFO - spectrum)

[7.zip](https://github.com/psi4/psi4webmo/files/294230/7.zip)

**Comment by loriab** [comment]
FYI, Psi4 doesn't compute intensities yet.

**Comment by polikw** [comment]
Well, I guess this issue is closed until spectral intensities are available.  :)
