### ISSUE TITLE
Molecular Orbital Symmetry

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#14]
The Symmetry of each MO is reported in the output file (right below the energy), but it is evidently not parsed.  Therefore the WebMO View Jobs page does not list the MO symmetries.  (job 8: CHFO - symmetry)

[8.zip](https://github.com/psi4/psi4webmo/files/294233/8.zip)

**Comment by bwb314** [comment]
This issue has been fixed with commit 1d8dd39.

**Comment by polikw** [comment]
Excellent!  MO symmetries are now parsed.
