### ISSUE TITLE
2-D Coordinate Scans

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#17]
2-D coordinate scans did not calculate anything (job 16: H2O - 2D)

[16.zip](https://github.com/psi4/psi4webmo/files/294248/16.zip)

**Comment by bwb314** [comment]
This seems to work for me. The range given to generate s1vals in the example is an empty set, which leads to no computations being requested. 

[scan_output.txt](https://github.com/psi4/psi4webmo/files/307496/scan_output.txt)

**Comment by polikw** [comment]
I agree.  2-D scans work, which I have verified with job 28 in the google cloud instance of WebMO 16.1.003rc1 / Psi4 1.0rc5

In Job 16, something happened somewhere to generate a nonsensical set of variable for s1vals:

> s1vals = [x*-36.2666666666667+110.0 for x in range(int(round(abs(1.2-110.0)/-36.2666666666667))+1)]
