### ISSUE TITLE
Optimize and Frequencies - Geometry Sequence Energies parsing

### ISSUE THREAD

**Issue by dbmagers** [psi4/psi4webmo#18]
When a Optimize and Frequencies job is selected the parsing of the energies is not smart enough to stop after the end of the optimization.  The result is a listing of additional steps for each displacement needed for the frequencies.

For an example see Job 10 on polikw's Google Cloud Server ([http://104.197.158.156/webmo](url)) under the Geometry Sequence Energies section.  See issue #11.

**Comment by bwb314** [comment]
This problem has been fixed with commits 8dac788 and 855fc41.
