### ISSUE TITLE
More than one Additional Keywords

### ISSUE THREAD

**Issue by dbmagers** [psi4/psi4webmo#19]
The Additional Keywords (comma delim.) under the Advanced tab of the Configure PSI4 Job Options does not seem to be compatible with PSI4's input structure.

Currently whatever is typed into that field is inserted verbatim as a line in the input file commas included.

Ex.  Additional Keywords:  set freeze_core true, set molden_write true

PSI4 throws an error for invalid syntax.

Maybe each delimitation should be a separate line with the commas removed.  Also currently the user needs to include the word "set" since the keywords are listed separately and not included in a set block.  I'm not sure if we want it that way or not, but wanted to mention it.

**Comment by bwb314** [comment]
Multiple arguments now appear on separate lines with commit f4a9828. Also, I implemented your suggestion of putting all additional keywords in the same set block with commit a182dca. We can change this back if we decide this isn't the way we want to do this, but I believe it is more user friendly to not require the user to prepend 'set' to each argument.
