### ISSUE TITLE
line endings on html files

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#2]
OK, now for a real issue!

When I downloaded the zip archive of these files, I did a diff from our previous distribution and discovered that the two html files
    \* psi.html
    \* psimgr_admin.html
have windows-style CR-LF line endings rather than the unit style LF line endings that WebMO uses.  I'm not concerned with how this difference was introduced, but rather just want to fix it.

Is the proper procedure your someone to convert the two files and them re-commit them?  Or is it to to tell GitHub that these files (and all other files) should follow the unix convention?

I might naively have tried the former, but the following GitHub documentation suggests that the latter is the right way to go:
    https://help.github.com/articles/dealing-with-line-endings/
What do you think?  Should someone create a .gitattributes file in the repository to fix this?  Or something else?

**Comment by loriab** [comment]
Huh, I've never encountered this before, as we're so uniformly OSX/Linux. I would naively have tried the former, too, but I agree that the `.gitattributes` procedure they recommend is the way to go. Go ahead with it. Or, we're doing a Psi4/WebMO workday tomorrow with Matt, so we'll do it if you don't.

**Comment by polikw** [comment]
Maybe it's the fact that they are *.html files.  Since I'm just getting started with GitHub, I would encourage you guys to do this.

**Comment by loriab** [comment]
Sure, I'll do it tomorrow.

**Comment by loriab** [comment]
All files forced LF upon checkout according to `.gitattributes` file. Reopen issue if not resolved as promised.

**Comment by polikw** [comment]
Verified that this has been fixed.  Thanks!
