### ISSUE TITLE
Method SSAPT0 option

### ISSUE THREAD

**Issue by dbmagers** [psi4/psi4webmo#20]
Currently when a SAPT calculation type is selected one of the method choices is SSAPT0.  It is my current understanding that the exchange-scaling SAPT0 (sSAPT0) is not a valid choice and included for free when requesting SAPT0.  See [http://psicode.org/psi4manual/master/sapt.html#sapt0](url)

So I think line 28 from [https://github.com/psi4/psi4webmo/blob/master/psi.html#L28](url) can be removed, but wanted to check with @loriab first.

**Comment by loriab** [comment]
It's true that you get sSAPT0 for free with a SAPT0 calc in the output file. However the value returned from `e = energy('ssapt0')` will be different from `e = energy('sapt0')`. (Or should be– I haven't made my final SAPT psivar checking pass yet.) So whether the separate choice in L28 should be removed depends on (i) if webmo does anything with returned values or only deals with parsed output and (ii) if classroom instructors want to be able to tell students to run ssapt0 specifically. 

That's the background. Whatever you decide is fine by me.

**Comment by loriab** [comment]
Turns out `energy('ssapt0')` isn't valid anyway. So removed it in ed7e224c6b1786e05b0182ed91d0ad6ff5ff75d4

**Comment by polikw** [comment]
Removing this line has the side effect of making the default SAPT method equal to SAPT2 (instead of SAPT0).

You also need to edit psi.js and change line 32 from
    form.method.selectedIndex = 7;
to
    form.method.selectedIndex = 6;
which will select the 6'th item ion the list (SAPT0) rather than the 7th (SAPT2).

**Comment by bwb314** [comment]
SAPT0 is now the default method for SAPT jobs with commit 4e6c566.

**Comment by polikw** [comment]
Yes, I have verified that SAPT0 is the default method for SAPT calculation types.  Thank you!
