### ISSUE TITLE
PSI4 scratch location when running through WebMO

### ISSUE THREAD

**Issue by jrschmidt2** [psi4/psi4webmo#22]
I believe that the run_psi.cgi should set the PSI_SCRATCH variable to $jobScratch.  Right now I believe PSI4 is not placing the scratch files where WebMO thinks it should and thus things are not getting cleaned up properly.

I don't have a working installation of PSI4 to test this (system too old to easily install it!)

**Comment by loriab** [comment]
Your `ldd --version` minor number is <7? If so, definitely too old for binary.

@bwb314 , do we have a working WebMO somewhere? It looks like should add a `-s $jobScratch` to https://github.com/psi4/psi4webmo/blob/master/cgi-bin/run_psi.cgi#L55 according to http://psicode.org/psi4manual/master/external.html#cmdoption-psi4-s . But we'd have to test it.

**Comment by bwb314** [comment]
This seems to fix the problem. Psi4 scratch files are being stored in the location specified by $jobScratch now.
