### ISSUE TITLE
psi.tmpl: set globals vs. set option

### ISSUE THREAD

**Issue by polikw** [psi4/psi4webmo#3]
In terms of template style, I think it would be more readable if Matt and Lori could convert "set globals{...}" constructs to separate "set option value" lines in psi.tmpl.  Decoupling these items would allow for easier maintenance of the templates.  But how would it impact the running of psi4?

**Comment by loriab** [comment]
How convenient, Matt was just doing those edits! 

It would make no difference to the running of psi4. Both `set {...}` and sequences of `set option val` get parsed into the same python commands for execution.

**Comment by loriab** [comment]
I think @matthewkennedy6 completed these changes, so closing the issue.
