### ISSUE TITLE
Dipole moment drawn incorrectly for water (DF-SCF optimization)

### ISSUE THREAD

**Issue by dbmagers** [psi4/psi4webmo#7]
I ran a DF-SCF/STO-3G geometry optimization on water and got the resulting dipole shown in the picture below, which is obviously incorrect.  This does not happen if you just run a DF-SCF single point.  I could not get this error to reproduce for another molecule, though I only tried one other (methanol).

![water_dipole](https://cloud.githubusercontent.com/assets/3967251/12878714/709d552c-cdf7-11e5-8c57-63d8b4ec5534.png)

**Comment by matthewkennedy6** [comment]
Can you copy the input file that it ran and send it to me at matthew.kennedy.6@gmail.com?

**Comment by polikw** [comment]
WebMO just parses the output file for the dipole moment vector.  Could you ALSO attach the psi OUTPUT file so that we can all see what is being parsed?

If it is not a praising problem, then I would guess that there is some mismatch in molecular vs. dipole coordinate system.

**Comment by dbmagers** [comment]
[output_h2o_dipoleproblem.txt](https://github.com/psi4/psi4webmo/files/122242/output_h2o_dipoleproblem.txt)

At a quick glance I believe this is a parsing problem since the molecule is in the yz plane and the reported dipole is in the z direction.

**Comment by CDSherrill** [comment]
Hi everyone,

   Brandon Bakr and I played around with this a bit today.

   I believe the dipole moment is being parsed correctly in Psi4.  However,
I think it is being drawn on top of the WebMO picture of the molecule which
is still in the original WebMO reference frame.  We need to get WebMO to
read the final optimized geometry in the Psi4 frame and display that at the
end of the optimization.  How do we do that?  I tried to look at other
interfaces like Q-Chem and I did not see any things there that were missing
for Psi4, but I guess I don't know where to look.

David

**Comment by CDSherrill** [comment]
Alternatively, I suppose it's possible that all other programs besides Psi4 accept the WebMO reference frame and always work in that frame, never reorienting to their own preferred frame.  That seems unlikely to me, though, because that would make it harder to utilize symmetry.

**Comment by jrschmidt2** [comment]
Note that there is no "WebMO" reference coordinate system.  It reads the geometry from the output file, using that coordinate system.  As long as the dipole moment is calculated / output in a consistent coordinate system, it will be displayed correctly.

Note that it is possible that the "wrong" geometry is being parsed by WebMO, e.g. it may be written in the output file in several places with inconsistent coordinate systems.  In that case, just make sure to read/parse the right one!

**Comment by CDSherrill** [comment]
Aha, very helpful.

Which routine is the one that is used to parse the final geometry of a
geometry optimization and update the picture of the molecule in the WebMO
window?  Would that be parse_psi_geometry()?  Are the results of
parse_psi_geometry_sequence() simply stored in case the user asks to view
the sequence?

**Comment by jrschmidt2** [comment]
You are correct on both accounts.

**Comment by CDSherrill** [comment]
I think I see what's happening... parse_psi_geometry() fails because the
number of atoms is not in this particular output.  Matt already fixed
parse_psi_geometry_sequence() last week to overcome exactly this problem.
Brandon Bakr is going to try to implement similar changes to
parse_psi_geometry() to see if that fixes it.

**Comment by bwb314** [comment]
I have just checked in a fix for this issue. David was exactly right in that the final geometry was not being pulled from the output due to the number of atoms not being in this output. 13b4c8c2e4ae9cf0f13d2639cdc5963dda77ad53

**Comment by loriab** [comment]
Aha, I was confused for a bit. @bwb314, if you change your identity on that vergil psi4webmo repo by resetting name and email according to the directions at https://github.com/cdsgroup/papers/blob/master/README.rst, your checkins will appear as you rather than Matt.

**Comment by bwb314** [comment]
Thank you for bringing this to my attention. I have fixed this for future purposes.
